meta:
  environment: ~

update:
  canaries: 0
  max_in_flight: 50
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: true

jobs:
  - name: consul
    instances: 3
    templates:
    - name: consul
      release: consul
    resource_pool: small_z1
    properties:
      consul:
        services:
      networks:
        apps: consul1
    persistent_disk: 0
    update:
      canaries: 0
      max_in_flight: 50
  - name: consul_client
    instances: 3
    templates:
    - name: consul
      release: consul
    resource_pool: small_z1
    properties:
      consul:
        server: false
        services:
      networks:
        apps: consul1
    persistent_disk: 0
    update:
      canaries: 0
      max_in_flight: 50
properties: {}
